;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Thu May 21 2026
; Processor: 80C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Start

;====================================================================
; CODE SEGMENT
;====================================================================

      org   0100h

Start:
    MOV P2, #00h
    CLR A

Press:
    JB P1.0, Press
    CALL Decoder

Release:
    JNB P1.0, Release
    INC A
    CALL Decoder
    CALL Delay3s        ; start 3s delay after displaying
    JB P1.0, Blank      ; if no press, blank the display
    LJMP Release        ; if pressed during delay, handle it
Blank:
    MOV P2, #00H
    LJMP Press

; ---- 3 Second Delay with button check every 100ms ----
Delay3s:
    MOV R5, #30         ; 30 x 100ms = 3 seconds
D1: CALL Wait100ms
    JNB P1.0, ExitDelay ; button pressed? exit early
    DJNZ R5, D1
    RET

ExitDelay:
    RET

Wait100ms:
    MOV R6, #200        ; 200 x 500us = 100ms
D2: MOV R7, #250        ; 250 x 2us = 500us
D3: DJNZ R7, D3
    DJNZ R6, D2
    RET

Decoder:
    CJNE A, #0, G1
    MOV P2, #3FH
    RET
G1:
    CJNE A, #1, G2
    MOV P2, #06H
    RET
G2:
    CJNE A, #2, G3
    MOV P2, #5BH
    RET
G3:
    CJNE A, #3, G4
    MOV P2, #4FH
    RET
G4:
    CJNE A, #4, G5
    MOV P2, #66H
    RET
G5:
    CJNE A, #5, G6
    MOV P2, #6DH
    RET
G6:
    CJNE A, #6, G7
    MOV P2, #7DH
    RET
G7:
    CJNE A, #7, G8
    MOV P2, #07H
    RET
G8:
    CJNE A, #8, G9
    MOV P2, #7FH
    RET
G9:
    CJNE A, #9, GA
    MOV P2, #6FH
    RET
GA:
    MOV P2, #3FH
    CLR A
    RET

END